services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9173"]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 9173:9173
